<%@ Page Title="" Language="C#" MasterPageFile="~/MainForm.Master" AutoEventWireup="true" CodeBehind="BookBus.aspx.cs" Inherits="BusBookingSystem.BookBus" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mainForm" runat="server">
    <div>
        <asp:GridView ID="Grid" runat="server" AutoGenerateColumns="False" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" DataKeyNames="BusId" 
            AutoGenerateDeleteButton="True" ShowFooter="True" AutoGenerateEditButton="True" OnRowDeleting="Grid_RowDeleting" OnRowEditing="Grid_RowEditing" 
            OnRowCancelingEdit="Grid_RowCancelingEdit" CellPadding="2" OnRowUpdating="Grid_RowUpdating">
            <Columns>
                 <asp:TemplateField HeaderText="S.No">
                    <ItemTemplate>
                        <asp:Label ID="lblSerialNumber" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:LinkButton ID ="btnInsert" Text ="Add" runat ="server" OnClick="BtnInsert_Click" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="BusType">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtType" runat="server" Text='<%# Bind("BusType") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("BusType") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert1" Placeholder="BusType" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="No. Of Seats">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtSeats" runat="server" Text='<%# Bind("Seats") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Seats") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert2" Placeholder="Seats" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Source">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtSource" runat="server" Text='<%# Bind("Source") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Source") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert3" Placeholder="Source" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Destination">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtDestination" runat="server" Text='<%# Bind("Destination") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Destination") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert4" Placeholder="Destination" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="ArrivalTime">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtATime" runat="server" Text='<%# Bind("ArrivalTime") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("ArrivalTime") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert5" Placeholder="ArrivalTime" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="DepartureTime">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtDTime" runat="server" Text='<%# Bind("DepartureTime") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("DepartureTime") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert6" Placeholder="DepartureTime" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Fare">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtFare" runat="server" Text='<%# Bind("Fare") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("Fare") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID ="BtnInsert7" Placeholder="Fare" runat ="server"/>
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>
</asp:Content>
